name: Vue.js CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài đặt Node.js phiên bản 18.5.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      # Cài đặt dependencies và build ứng dụng Vue.js
      - name: Install and Build Vue.js
        run: |
          npm install
          npm run build

      # Lưu trữ artifact build cho deploy
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vue-build
          path: dist # Đường dẫn đến thư mục build của Vue.js

  deploy:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập SSH Agent và add SSH private key
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Check SSH connection
        run: ssh -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}

      # Tải artifact build Vue.js
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: vue-build
          path: vue_build # Thư mục tạm để lưu trữ artifact

      # Deploy tới server qua SSH
      - name: Deploy to server
        run: |
          scp -r $GITHUB_WORKSPACE/vue_build/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/vue_build_tmp
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            mkdir -p frontend/admin
            cd frontend/admin
            rm -rf *
            cp -r ~/vue_build_tmp/* .
            rm -rf ~/vue_build_tmp
            echo "Frontend deployment completed successfully!"
          EOF

